### ISSUE TITLE
[feature request] customize the download path

### ISSUE THREAD

**Issue by taseikyo** [amarjeetmalpotra/yt-downloader#1]
It will be cooler, if it is able to customize the download path :P

**Comment by ghost** [comment]
@taseikyo
Got it covered 😉
[Commit #10](https://github.com/amarjeetmalpotra/yt-downloader/commit/3bb5e47181074dbc7d9ffa58c7f32f06017f1c66)

**Comment by taseikyo** [comment]
great! 👍
